"""DA execution endpoints for chat-backed Pyodide flows."""

import mimetypes
import os
from typing import (
    Optional,
)

from fastapi import (
    Depends,
    File,
    Form,
    HTTPException,
    Query,
    status,
    UploadFile,
    WebSocket,
    WebSocketDisconnect,
)

from galaxy.managers.agents import AgentService
from galaxy.managers.chat import ChatManager
from galaxy.managers.chat_execution import ChatExecutionService
from galaxy.managers.chat_execution_streams import ChatExecutionStreamsManager
from galaxy.managers.context import ProvidesHistoryContext
from galaxy.model import (
    HistoryDatasetAssociation,
    User,
)
from galaxy.schema.agents import UploadedArtifact
from galaxy.schema.fields import DecodedDatabaseIdField
from galaxy.schema.schema import PyodideResultPayload
from galaxy.webapps.galaxy.api import (
    depends,
    get_app,
    get_user,
    DependsOnTrans,
    DependsOnUser,
    Router,
)
from galaxy.work.context import WorkRequestContext

router = Router(tags=["chat"])


def _guess_extension(filename: Optional[str], mime_type: Optional[str]) -> str:
    if filename and "." in filename:
        candidate = filename.rsplit(".", 1)[1].strip().lower()
        if candidate:
            return candidate
    if mime_type:
        guessed = mimetypes.guess_extension(mime_type)
        if guessed:
            return guessed.lstrip(".")
    return "data"


@router.cbv
class ChatExecutionAPI:
    chat_manager: ChatManager = depends(ChatManager)
    agent_service: AgentService = depends(AgentService)
    chat_execution_service: ChatExecutionService = depends(ChatExecutionService)
    chat_execution_streams: ChatExecutionStreamsManager = depends(ChatExecutionStreamsManager)

    @router.post("/api/chat/exchange/{exchange_id}/artifacts")
    async def upload_pyodide_artifact(
        self,
        exchange_id: DecodedDatabaseIdField,
        file: UploadFile = File(...),
        name: Optional[str] = Form(default=None),
        mime_type: Optional[str] = Form(default=None),
        size: Optional[int] = Form(default=None),
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ) -> UploadedArtifact:
        """Persist an artifact generated by the Pyodide worker as a history dataset."""

        exchange = self.chat_manager.get_exchange_by_id(trans, exchange_id)
        if not exchange:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Chat exchange not found")

        history = trans.history
        if history is None:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No active history available")

        raw_bytes = await file.read()
        if not raw_bytes:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Artifact contains no data")

        artifact_name = name or file.filename or "artifact"
        artifact_mime = mime_type or file.content_type or "application/octet-stream"
        artifact_size = size or len(raw_bytes)
        extension = _guess_extension(artifact_name, artifact_mime)

        hda = HistoryDatasetAssociation(
            history=history,
            name=artifact_name,
            extension=extension,
            create_dataset=True,
            sa_session=trans.sa_session,
        )
        trans.sa_session.add(hda)
        history.add_dataset(hda, set_hid=True)

        permissions = trans.app.security_agent.history_get_default_permissions(history)
        trans.app.security_agent.set_all_dataset_permissions(hda.dataset, permissions, new=True, flush=False)

        dataset = hda.dataset
        try:
            trans.app.object_store.create(dataset)
        except Exception as exc:  # pragma: no cover - object store allocation failure
            trans.sa_session.rollback()
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc)) from exc

        file_path = dataset.get_file_name()
        try:
            with open(file_path, "wb") as handle:
                handle.write(raw_bytes)
        except Exception as exc:
            trans.sa_session.rollback()
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc)) from exc

        hda.state = hda.states.OK
        try:
            hda.set_size()
            hda.set_total_size()
        except Exception:
            pass
        try:
            hda.set_meta()
        except Exception:
            pass
        try:
            hda.set_peek()
        except Exception:
            pass

        trans.sa_session.flush()
        trans.sa_session.commit()

        encoded_dataset_id = trans.security.encode_id(hda.id)
        download_url = self.agent_service._dataset_download_url(trans, encoded_dataset_id)
        return UploadedArtifact(
            dataset_id=encoded_dataset_id,
            history_id=trans.security.encode_id(history.id),
            name=artifact_name,
            mime_type=artifact_mime,
            size=artifact_size,
            download_url=download_url,
        )

    @router.websocket("/api/chat/exchange/{exchange_id}/stream")
    async def chat_exchange_stream(
        self,
        exchange_id: DecodedDatabaseIdField,
        websocket: WebSocket,
        app=Depends(get_app),
        user: Optional[User] = Depends(get_user),
    ) -> None:
        if user is None:
            await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
            return
        trans = WorkRequestContext(app=app, user=user)
        exchange = self.chat_manager.get_exchange_by_id(trans, exchange_id)
        if exchange is None:
            await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
            return

        await websocket.accept()
        await self.chat_execution_streams.register(exchange_id, websocket)
        try:
            while True:
                try:
                    message = await websocket.receive_text()
                except WebSocketDisconnect:
                    break
                if message and message.lower().startswith("ping"):
                    await websocket.send_text("pong")
        except WebSocketDisconnect:
            pass
        finally:
            await self.chat_execution_streams.remove(exchange_id, websocket)

    @router.post("/api/chat/exchange/{exchange_id}/pyodide_result")
    async def submit_pyodide_result(
        self,
        exchange_id: DecodedDatabaseIdField,
        payload: PyodideResultPayload,
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ) -> dict[str, object]:
        """Persist results from client-side Pyodide execution and trigger follow-up reasoning."""

        exchange = self.chat_manager.get_exchange_by_id(trans, exchange_id)
        if not exchange:
            return {"message": "Chat exchange not found"}

        response_payload = await self.chat_execution_service.handle_pyodide_result(exchange_id, payload, trans, user)
        if response_payload.get("agent_response"):
            await self.chat_execution_streams.broadcast_exec_followup(
                exchange_id,
                {
                    "type": "exec_followup",
                    "exchange_id": exchange_id,
                    "task_id": payload.task_id,
                    "payload": response_payload,
                },
            )
        return response_payload

    @router.get("/api/chat/datasets/{dataset_id}/download")
    async def download_dataset_for_execution(
        self,
        dataset_id: str,
        token: str = Query(..., description="Signed dataset download token"),
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ):
        """Stream a history dataset referenced by a signed execution token."""

        if not token:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Missing download token")

        try:
            self.agent_service.verify_dataset_download_token(trans, dataset_id, token)
        except ValueError as exc:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(exc)) from exc

        try:
            decoded_id = trans.security.decode_id(dataset_id)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Dataset not found") from exc

        hda_manager = trans.app.hda_manager
        try:
            hda = hda_manager.get_accessible(decoded_id, user, current_history=trans.history, trans=trans)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Dataset is not accessible") from exc

        try:
            hda_manager.ensure_dataset_on_disk(trans, hda)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

        dataset = hda.dataset
        file_path = dataset.get_file_name()
        if not file_path or not os.path.exists(file_path):
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Dataset file not found")

        mime_type = hda.get_mime() or "application/octet-stream"
        try:
            display_name = hda.display_name()
        except Exception:
            display_name = hda.name or dataset_id
        safe_name = (display_name or dataset_id).replace("\\", "").replace('"', "")
        headers = {
            "Content-Disposition": f'attachment; filename="{safe_name}"',
            "Content-Length": str(os.path.getsize(file_path)),
        }

        def iter_file():
            with open(file_path, "rb") as handle:
                while True:
                    chunk = handle.read(65536)
                    if not chunk:
                        break
                    yield chunk

        from starlette.responses import StreamingResponse

        return StreamingResponse(iter_file(), media_type=mime_type, headers=headers)
