"""Data analysis chat execution endpoints for chat-backed Pyodide flows."""

import os
from typing import (
    Optional,
)

from fastapi import (
    Depends,
    File,
    Form,
    HTTPException,
    Query,
    status,
    UploadFile,
    WebSocket,
    WebSocketDisconnect,
)

from galaxy.exceptions import (
    InternalServerError,
    ObjectNotFound,
    RequestParameterInvalidException,
)
from galaxy.managers.agents import AgentService
from galaxy.managers.chat import ChatManager
from galaxy.managers.chat_execution_streams import ChatExecutionStreamsManager
from galaxy.managers.context import ProvidesHistoryContext
from galaxy.managers.data_analysis_chat_artifacts import DataAnalysisChatArtifactsManager
from galaxy.managers.data_analysis_chat_execution import DataAnalysisChatExecutionManager
from galaxy.model import User
from galaxy.schema.agents import UploadedArtifact
from galaxy.schema.fields import DecodedDatabaseIdField
from galaxy.schema.schema import PyodideResultPayload
from galaxy.webapps.galaxy.api import (
    depends,
    get_app,
    get_user,
    DependsOnTrans,
    DependsOnUser,
    Router,
)
from galaxy.work.context import WorkRequestContext

router = Router(tags=["chat"])


@router.cbv
class DataAnalysisChatExecutionAPI:
    chat_manager: ChatManager = depends(ChatManager)
    agent_service: AgentService = depends(AgentService)
    chat_execution_streams: ChatExecutionStreamsManager = depends(ChatExecutionStreamsManager)
    data_analysis_chat_artifacts_manager: DataAnalysisChatArtifactsManager = depends(DataAnalysisChatArtifactsManager)
    data_analysis_chat_execution_manager: DataAnalysisChatExecutionManager = depends(DataAnalysisChatExecutionManager)

    @router.post("/api/chat/exchange/{exchange_id}/artifacts")
    async def upload_pyodide_artifact(
        self,
        exchange_id: DecodedDatabaseIdField,
        file: UploadFile = File(...),
        name: Optional[str] = Form(default=None),
        mime_type: Optional[str] = Form(default=None),
        size: Optional[int] = Form(default=None),
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ) -> UploadedArtifact:
        """Persist an artifact generated by the Pyodide worker as a history dataset."""

        raw_bytes = await file.read()
        artifact_name = name or file.filename or "artifact"
        artifact_mime = mime_type or file.content_type or "application/octet-stream"
        try:
            return self.data_analysis_chat_artifacts_manager.create_artifact(
                exchange_id=exchange_id,
                trans=trans,
                raw_bytes=raw_bytes,
                name=artifact_name,
                mime_type=artifact_mime,
                size=size,
            )
        except ObjectNotFound as exc:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
        except RequestParameterInvalidException as exc:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
        except InternalServerError as exc:
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc)) from exc

    @router.websocket("/api/chat/exchange/{exchange_id}/stream")
    async def chat_exchange_stream(
        self,
        exchange_id: DecodedDatabaseIdField,
        websocket: WebSocket,
        app=Depends(get_app),
        user: Optional[User] = Depends(get_user),
    ) -> None:
        if user is None:
            await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
            return
        trans = WorkRequestContext(app=app, user=user)
        exchange = self.chat_manager.get_exchange_by_id(trans, exchange_id)
        if exchange is None:
            await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
            return

        await websocket.accept()
        await self.chat_execution_streams.register(exchange_id, websocket)
        try:
            while True:
                try:
                    message = await websocket.receive_text()
                except WebSocketDisconnect:
                    break
                if message and message.lower().startswith("ping"):
                    await websocket.send_text("pong")
        except WebSocketDisconnect:
            pass
        finally:
            await self.chat_execution_streams.remove(exchange_id, websocket)

    @router.post("/api/chat/exchange/{exchange_id}/pyodide_result")
    async def submit_pyodide_result(
        self,
        exchange_id: DecodedDatabaseIdField,
        payload: PyodideResultPayload,
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ) -> dict[str, object]:
        """Persist results from client-side Pyodide execution and trigger follow-up reasoning."""

        try:
            return await self.data_analysis_chat_execution_manager.submit_pyodide_result(exchange_id, payload, trans, user)
        except ObjectNotFound:
            return {"message": "Chat exchange not found"}

    @router.get("/api/chat/datasets/{dataset_id}/download")
    async def download_dataset_for_execution(
        self,
        dataset_id: str,
        token: str = Query(..., description="Signed dataset download token"),
        trans: ProvidesHistoryContext = DependsOnTrans,
        user: User = DependsOnUser,
    ):
        """Stream a history dataset referenced by a signed execution token."""

        if not token:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Missing download token")

        try:
            self.agent_service.verify_dataset_download_token(trans, dataset_id, token)
        except ValueError as exc:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(exc)) from exc

        try:
            decoded_id = trans.security.decode_id(dataset_id)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Dataset not found") from exc

        hda_manager = trans.app.hda_manager
        try:
            hda = hda_manager.get_accessible(decoded_id, user, current_history=trans.history, trans=trans)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Dataset is not accessible") from exc

        try:
            hda_manager.ensure_dataset_on_disk(trans, hda)
        except Exception as exc:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

        dataset = hda.dataset
        file_path = dataset.get_file_name()
        if not file_path or not os.path.exists(file_path):
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Dataset file not found")

        mime_type = hda.get_mime() or "application/octet-stream"
        try:
            display_name = hda.display_name()
        except Exception:
            display_name = hda.name or dataset_id
        safe_name = (display_name or dataset_id).replace("\\", "").replace('"', "")
        headers = {
            "Content-Disposition": f'attachment; filename="{safe_name}"',
            "Content-Length": str(os.path.getsize(file_path)),
        }

        def iter_file():
            with open(file_path, "rb") as handle:
                while True:
                    chunk = handle.read(65536)
                    if not chunk:
                        break
                    yield chunk

        from starlette.responses import StreamingResponse

        return StreamingResponse(iter_file(), media_type=mime_type, headers=headers)
